import requests
import json
import time
import random
import string
import sqlite3
import time
from datetime import datetime, timezone
from interactions import Embed
import traceback
import pytz
from dateutil import parser 

searchClanHeader = {
    'authorization' : 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImVjNWVkODY2LWVmMzctNDZjYi1hOTM4LWUzMWFlMmE3YjhhMCIsImlhdCI6MTY4NjQxNDM2Nywic3ViIjoiZGV2ZWxvcGVyLzc4ZjdjMzM2LWM2NjUtYzdmYi0xYzhkLTE0YjlhZTY4NjEwMiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjgxLjY0LjI1NS4xMTkiXSwidHlwZSI6ImNsaWVudCJ9XX0.J_1HMMjTeUzEndQ30VTCP582vqH6rpnQw01qdIsM6I9RZ0HWOiZw9wtvlhdePfvnUHvwAKGv8Ql3rCoBR80S2Q'
}

searchPlayerHeader = {
    'authorization' : 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijk5ZmU5NmUxLWRjODktNGM2Zi05Mjg0LTg2OTFmOGRhYjUyNCIsImlhdCI6MTY4NjQxNDM5MCwic3ViIjoiZGV2ZWxvcGVyLzc4ZjdjMzM2LWM2NjUtYzdmYi0xYzhkLTE0YjlhZTY4NjEwMiIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjgxLjY0LjI1NS4xMTkiXSwidHlwZSI6ImNsaWVudCJ9XX0.pDhhspnsGDlUY1I-xkNVVOmGznFgoL-rgTZQmHTzIN1GEMalK5MzAId3tlutSDwDsJqKmFjr54FOkenDaTgCCQ'
}

starTime = "20230623T181536.000Z"
starTime = parser.parse(starTime)

time_difference = datetime.now(timezone.utc) - starTime

# Extraction des heures, minutes et secondes
hours = time_difference.seconds // 3600
minutes = (time_difference.seconds % 3600) // 60
seconds = time_difference.seconds % 60
print("Durée : {} heures, {} minutes, {} secondes".format(int(hours), int(minutes), int(seconds)))