betterTroops = {
    "townHallLevel": [
        { # 1
            "Barbare": 1,
            "Archer": 1,
            "géant": 1,
        },
        { # 2
            "Barbare": 1,
            "Archer": 1,
            "géant": 1,
            "gobelin": 1,
        },
        { # 3
            "Barbare": 2,
            "Archer": 2,
            "géant": 1,
            "gobelin": 2,
            "sapeur": 1,
            "sortDeFoudre": 2,
        },
        { # 4
            "Barbare": 2,
            "Archer": 2,
            "géant": 2,
            "gobelin": 2,
            "sapeur": 2,
            "ballon": 2,
            "sortDeFoudre": 3,
        },
        {# 5
            "Barbare": 3,
            "Archer": 3,
            "géant": 2,
            "gobelin": 3,
            "sapeur": 2,
            "ballon": 2,
            "sorcier": 2,
            "sortDeFoudre":4,
        },
        { # 6
            "Barbare": 3,
            "Archer": 3,
            "géant": 3,
            "gobelin": 3,
            "sapeur": 3,
            "ballon": 3,
            "sorcier": 3,
            'guérisseuse': 1,
            "sortDeFoudre": 4,
            "sortDeGuérison": 3,
            "sortDeRage": 3,
        },
        { # 7
            "Barbare": 4,
            "Archer": 4,
            "géant": 4,
            "gobelin": 4,
            "sapeur": 4,
            "ballon": 4,
            "sorcier": 4,
            'guérisseuse': 2,
            "dragon": 2,
            "sortDeFoudre": 4,
            "sortDeGuérison": 4,
            "sortDeRage": 4,
            "sortDePoison": 1,
            "gargouille": 2,
            "cochon": 2,
            "RoiDesBarbares": 5,
        },
        { # 8
            "Barbare": 5,
            "Archer": 5,
            "géant": 5,
            "gobelin": 5,
            "sapeur": 5,
            "ballon": 5,
            "sorcier": 5,
            'guérisseuse': 3,
            "dragon": 3,
            "P.E.K.K.A": 3,
            "sortDeFoudre": 5,
            "sortDeGuérison": 5,
            "sortDeRage": 5,
            "sortDePoison": 2,
            "sortSismique": 2,
            "gargouille": 4,
            "cochon": 4,
            "Valkyrie": 2,
            "golem": 2,
            "RoiDesBarbares": 10,
        },
        { # 9
            "Barbare": 6,
            "Archer": 6,
            "géant": 6,
            "gobelin": 6,
            "sapeur": 5,
            "ballon": 6,
            "sorcier": 6,
            'guérisseuse': 4,
            "dragon": 4,
            "P.E.K.K.A": 4,
            "Bébé dragon": 2,
            "sortDeFoudre": 6,
            "sortDeGuérison": 6,
            "sortDeRage": 5,
            "sortDeSaut": 2,
            "sortDeGel": 2,
            "sortDePoison": 3,
            "sortSismique": 3,
            "sortDePrécipitation": 2,
            "gargouille": 5,
            "cochon": 5,
            "Valkyrie": 4,
            "golem": 4,
            "sorcière": 2,
            "molosse de lave": 2,
            "RoiDesBarbares": 30,
            "ReineDesArchères": 30,
        },
        { # 10
            "Barbare": 7,
            "Archer": 7,
            "géant": 7,
            "gobelin": 7,
            "sapeur": 6,
            "ballon": 6,
            "sorcier": 7,
            'guérisseuse': 4,
            "dragon": 5,
            "P.E.K.K.A": 6,
            "Bébé dragon": 4,
            "mineur": 3,
            "sortDeFoudre": 7,
            "sortDeGuérison": 7,
            "sortDeRage": 5,
            "sortDeSaut": 3,
            "sortDeGel": 5,
            "sortDeClonage": 3,
            "sortDePoison": 4,
            "sortSismique": 4,
            "sortDePrécipitation": 4,
            "sortSquelettique": 3,
            "sortDeBat": 3,
            "gargouille": 6,
            "cochon": 6,
            "Valkyrie": 5,
            "golem": 5,
            "sorcière": 3,
            "molosse de lave": 3,
            "bouliste": 2,
            "RoiDesBarbares": 40,
            "ReineDesArchères": 40,
        },
        { # 11
            "Barbare": 8,
            "Archer": 8,
            "géant": 8,
            "gobelin": 7,
            "sapeur": 7,
            "ballon": 7,
            "sorcier": 8,
            'guérisseuse': 5,
            "dragon": 6,
            "P.E.K.K.A": 7,
            "Bébé dragon": 5,
            "mineur": 5,
            "E-drag": 2,
            "sortDeFoudre": 8,
            "sortDeGuérison": 7,
            "sortDeRage": 5,
            "sortDeSaut": 3,
            "sortDeGel": 6,
            "sortDeClonage": 5,
            "sortInvisibilité": 2,
            "sortDePoison": 5,
            "sortSismique": 5,
            "sortDePrécipitation": 5,
            "sortSquelettique": 4,
            "sortDeBat": 4,
            "gargouille": 7,
            "cochon": 7,
            "Valkyrie": 6,
            "golem": 7,
            "sorcière": 4,
            "molosse de lave": 4,
            "bouliste": 3,
            "golem de glace": 3,
            "RoiDesBarbares": 50,
            "ReineDesArchères": 50,
            "warden": 20,
        },
        { # 12
            "Barbare": 9,
            "Archer": 9,
            "géant": 9,
            "gobelin": 8,
            "sapeur": 8,
            "ballon": 8,
            "sorcier": 9,
            'guérisseuse': 5,
            "dragon": 7,
            "P.E.K.K.A": 8,
            "Bébé dragon": 6,
            "mineur": 6,
            "E-drag": 3,
            "yeti": 2,
            "sortDeFoudre": 9,
            "sortDeGuérison": 7,
            "sortDeRage": 6,
            "sortDeSaut": 3,
            "sortDeGel": 7,
            "sortDeClonage": 5,
            "sortInvisibilité": 3,
            "sortDePoison": 6,
            "sortSismique": 5,
            "sortDePrécipitation": 5,
            "sortSquelettique": 6,
            "sortDeBat": 5,
            "gargouille": 8,
            "cochon": 9,
            "Valkyrie": 7,
            "golem": 9,
            "sorcière": 5,
            "molosse de lave": 5,
            "bouliste": 4,
            "golem de glace": 5,
            "chasseuse": 2,
            "Broyeur": 3,
            "dirigeable": 3,
            "Démolisseur": 3,
            "Catapulte": 3,
            "RoiDesBarbares": 65,
            "ReineDesArchères": 65,
            "warden": 40,
        },
        { # 13
            "Barbare": 9,
            "Archer": 9,
            "géant": 10,
            "gobelin": 8,
            "sapeur": 9,
            "ballon": 9,
            "sorcier": 10,
            'guérisseuse': 6,
            "dragon": 8,
            "P.E.K.K.A": 9,
            "Bébé dragon": 7,
            "mineur": 7,
            "E-drag": 4,
            "yeti": 3,
            "ChevaucheurDeDragon": 2,
            "sortDeFoudre": 9,
            "sortDeGuérison": 8,
            "sortDeRage": 6,
            "sortDeSaut": 4,
            "sortDeGel": 7,
            "sortDeClonage": 6,
            "sortInvisibilité": 4,
            "sortDeRappel": 2,
            "sortDePoison": 7,
            "sortSismique": 5,
            "sortDePrécipitation": 5,
            "sortSquelettique": 7,
            "sortDeBat": 5,
            "gargouille": 9,
            "cochon": 10,
            "Valkyrie": 8,
            "golem": 10,
            "sorcière": 5,
            "molosse de lave": 6,
            "bouliste": 5,
            "golem de glace": 5,
            "chasseuse": 3,
            "apprentiGardien": 2,
            "Broyeur": 4,
            "dirigeable": 4,
            "Démolisseur": 4,
            "Caserne": 4,
            "lanceBuches": 4,
            "Catapulte": 4,
            "RoiDesBarbares": 75,
            "ReineDesArchères": 75,
            "warden": 50,
            "championne": 25,
        },
        { # 14
            "Barbare": 10,
            "Archer": 10,
            "géant": 10,
            "gobelin": 8,
            "sapeur": 10,
            "ballon": 10,
            "sorcier": 10,
            'guérisseuse': 7,
            "dragon": 9,
            "P.E.K.K.A": 9,
            "Bébé dragon": 8,
            "mineur": 8,
            "E-drag": 5,
            "yeti": 4,
            "ChevaucheurDeDragon": 3,
            "éléctro-titanide": 2,
            "sortDeFoudre": 9,
            "sortDeGuérison": 8,
            "sortDeRage": 6,
            "sortDeSaut": 4,
            "sortDeGel": 7,
            "sortDeClonage": 7,
            "sortInvisibilité": 4,
            "sortDeRappel": 3,
            "sortDePoison": 8,
            "sortSismique": 5,
            "sortDePrécipitation": 5,
            "sortSquelettique": 7,
            "sortDeBat": 5,
            "gargouille": 10,
            "cochon": 11,
            "Valkyrie": 9,
            "golem": 11,
            "sorcière": 5,
            "molosse de lave": 6,
            "bouliste": 6,
            "golem de glace": 6,
            "chasseuse": 3,
            "apprentiGardien": 3,
            "Broyeur": 3,
            "dirigeable": 4,
            "Démolisseur": 4,
            "Caserne": 4,
            "lanceBuches": 4,
            "Catapulte": 4,
            "RoiDesBarbares": 80,
            "ReineDesArchères": 80,
            "warden": 55,
            "championne": 30,
        },
        { # 15
            "Barbare": 11,
            "Archer": 11,
            "géant": 11,
            "gobelin": 9,
            "sapeur": 11,
            "ballon": 10,
            "sorcier": 11,
            'guérisseuse': 8,
            "dragon": 10,
            "P.E.K.K.A": 10,
            "Bébé dragon": 9,
            "mineur": 9,
            "E-drag": 6,
            "yeti": 5,
            "ChevaucheurDeDragon": 3,
            "éléctro-titanide": 3,
            "sortDeFoudre": 10,
            "sortDeGuérison": 9,
            "sortDeRage": 6,
            "sortDeSaut": 5,
            "sortDeGel": 7,
            "sortDeClonage": 8,
            "sortInvisibilité": 4,
            "sortDeRappel": 4,
            "sortDePoison": 9,
            "sortSismique": 5,
            "sortDePrécipitation": 5,
            "sortSquelettique": 8,
            "sortDeBat": 6,
            "gargouille": 11,
            "cochon": 12,
            "Valkyrie": 10,
            "golem": 12,
            "sorcière": 6,
            "molosse de lave": 6,
            "bouliste": 7,
            "golem de glace": 7,
            "chasseuse": 3,
            "apprentiGardien": 4,
            "Broyeur": 5,
            "dirigeable": 4,
            "Démolisseur": 5,
            "Caserne": 4,
            "lanceBuches": 4,
            "Catapulte": 4,
            "foreuse": 4,
            "RoiDesBarbares": 90,
            "ReineDesArchères": 90,
            "warden": 65,
            "championne": 40,
        }
    ]
}
betterTroops = betterTroops["townHallLevel"]


hérosFR = [
    "RoiDesBarbares",
    "ReineDesArchères",
    "warden",
    "championne",
]

herosAPI = [
    "Barbarian King",
    "Archer Queen",
    "Grand Warden",
    "Royal Champion",
]






sortDataFR = [
            "sortDeFoudre",
            "sortDeGuérison",
            "sortDeRage",
            "sortDeSaut",
            "sortDeGel",
            "sortDeClonage",
            "sortInvisibilité",
            "sortDeRappel",
            "sortDePoison",
            "sortSismique",
            "sortDePrécipitation",
            "sortSquelettique",
            "sortDeBat",
]

sortAPI = [
            "Lightning Spell",
            "Healing Spell",
            "Rage Spell",
            "Jump Spell",
            "Freeze Spell",
            "Clone Spell",
            "Invisibility Spell",
            "Recall Spell",
            "Poison Spell",
            "Earthquake Spell",
            "Haste Spell",
            "Skeleton Spell",
            "Bat Spell",
]

emojiSortFR = {
            "sortDeFoudre" : "<:zz:1136771570283597844>",
            "sortDeGuérison" : "<:zz:1136771628894789743>",
            "sortDeRage" : "<:zz:1136771676068126851>",
            "sortDeSaut" : "<:zz:1136771730912858192>",
            "sortDeGel" : "<:zz:1136771766195339357>", 
            "sortDeClonage" : "<:zz:1136771800919982230>",
            "sortInvisibilité" : "<:zz:1136771835128729640>",
            "sortDeRappel" : "<:zz:1136771877642178581>",
            "sortDePoison" : "<:zz:1136771908373844059>",
            "sortSismique" : "<:zz:1136772015676739726>",
            "sortDePrécipitation" : "<:zz:1136772051940671560>",
            "sortSquelettique" : "<:zz:1136772101471223950>",
            "sortDeBat" : "<:zz:1136772131036856501>",
}

trpRoseFR = ["Barbare",
            "Archer",
            "géant",
            "gobelin",
            "sapeur",
            "ballon",
            "sorcier",
            "guérisseuse",
            "dragon",
            "P.E.K.K.A",
            "Bébé dragon",
            "mineur",
            "E-drag",
            "yeti",
            "ChevaucheurDeDragon",
            "éléctro-titanide",]

emojiTrpNoirFR = {
            "gargouille" : "<:aa:1136659430088380476>",
            "cochon" : "<:aa:1136659460182515803>",
            "Valkyrie" : "<:aa:1136659504008798308>",
            "golem" : "<:aa:1136659543267475556>",
            "sorcière" : "<:aa:1136659571088293968>",
            "molosse de lave" : "<:aa:1136659602247782480>",
            "bouliste" : "<:aa:1136659627552018463>",
            "golem de glace" : "<:aa:1136659664638058587>",
            "chasseuse" : "<:aa:1136659720921415731>",
            "apprentiGardien" : "<:aa:1136659754039656569>",
            }

trpNoirFR = ["gargouille",
            "cochon",
            "Valkyrie",
            "golem",
            "sorcière",
            "molosse de lave",
            "bouliste",
            "golem de glace",
            "chasseuse",
            "apprentiGardien",
            ]

trpNoirAPI = ["Minion",
            "Hog Rider",
            "Valkyrie",
            "Golem",
            "Witch",
            "Lava Hound",
            "Bowler",
            "Ice Golem",
            "Headhunter",
            "Apprentice Warden",
            ]

trpRoseAPI = ["Barbarian",
            "Archer",
            "Giant",
            "Goblin",
            "Wall Breaker",
            "Balloon",
            "Wizard",
            "Healer",
            "Dragon",
            "P.E.K.K.A",
            "Baby Dragon",
            "Miner",
            "Electro Dragon",
            "Yeti",
            "Dragon Rider",
            "Electro Titan",]

emojiTrpRoseFR = {
                "Barbare" : "<:pp:1136642319781744672>",
                "Archer" : "<:pp:1136642394461307020>",
                "géant" : "<:pp:1136642453345148928>",
                "gobelin" : "<:pp:1136642537650667550>",
                "sapeur" : "<:pp:1136642600707829820>",
                "ballon" : "<:pp:1136642645066784810>",
                "sorcier" : "<:pp:1136642682299633794>",
                "guérisseuse" : "<:pp:1136642719477940359>",
                "dragon" : "<:pp:1136642753292423188>",
                "P.E.K.K.A" : "<:JUSTPK:1136642844346560602>",
                "Bébé dragon" : "<:pp:1136642970217627679>",
                "mineur" : "<:pp:1136643057899548752>",
                "E-drag" : "<:pp:1136643122865131620>",
                "yeti" : "<:pp:1136643168260083793>",
                "ChevaucheurDeDragon" : "<:pp:1136643214468730920>",
                "éléctro-titanide" : "<:pp:1136643288716279878>",
            }
        

laboPNG = [
    "",
    "",
    "https://coc.guide/static/imgs/army/laboratory-1.png",
    "https://coc.guide/static/imgs/army/laboratory-2.png",
    "https://coc.guide/static/imgs/army/laboratory-3.png",
    "https://coc.guide/static/imgs/army/laboratory-4.png",
    "https://coc.guide/static/imgs/army/laboratory-5.png",
    "https://coc.guide/static/imgs/army/laboratory-6.png",
    "https://coc.guide/static/imgs/army/laboratory-7.png",
    "https://coc.guide/static/imgs/army/laboratory-8.png",
    "https://coc.guide/static/imgs/army/laboratory-9.png",
    "https://coc.guide/static/imgs/army/laboratory-10.png",
    "https://coc.guide/static/imgs/army/laboratory-11.png",
    "https://coc.guide/static/imgs/army/laboratory-12.png",
    "https://coc.guide/static/imgs/army/laboratory-13.png",

]

hdvPNG = [
    {
        "url": "https://coc.guide/static/imgs/other/town-hall-1.png",
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-2.png"
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-3.png"
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-4.png"
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-5.png"
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-6.png"
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-7.png"
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-8.png"
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-9.png"
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-10.png"
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-11.png"
    },
    {
        "url" : "https://coc.guide/static/imgs/other/town-hall-12.png"
    },
    {
        "th" : [
            "https://coc.guide/static/imgs/other/town-hall-13-1.png",
            "https://coc.guide/static/imgs/other/town-hall-13-2.png",
            "https://coc.guide/static/imgs/other/town-hall-13-3.png",
            "https://coc.guide/static/imgs/other/town-hall-13-4.png",
            "https://coc.guide/static/imgs/other/town-hall-13-5.png",
        ],
    },
    {
        "th" : [
            "https://coc.guide/static/imgs/other/town-hall-14-1.png",
            "https://coc.guide/static/imgs/other/town-hall-14-2.png",
            "https://coc.guide/static/imgs/other/town-hall-14-3.png",
            "https://coc.guide/static/imgs/other/town-hall-14-4.png",
            "https://coc.guide/static/imgs/other/town-hall-14-5.png",
        ],
    },
    {
        "th" : [
            "https://coc.guide/static/imgs/other/town-hall-15-1.png",
            "https://coc.guide/static/imgs/other/town-hall-15-2.png",
            "https://coc.guide/static/imgs/other/town-hall-15-3.png",
            "https://coc.guide/static/imgs/other/town-hall-15-4.png",
            "https://coc.guide/static/imgs/other/town-hall-15-5.png",
        ],
    },
]